//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDJArticle15.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddManager
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string rawHtml { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> width { get; set; }
        public string link { get; set; }
        public Nullable<int> viewCount { get; set; }
        public Nullable<int> clickCount { get; set; }
    }
}
