//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDJArticle15.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public article()
        {
            this.ArticleComments = new HashSet<ArticleComment>();
            this.ArticleFiles = new HashSet<ArticleFile>();
            this.ArticleImages = new HashSet<ArticleImage>();
            this.ArticleLinks = new HashSet<ArticleLink>();
            this.ArticleLikes = new HashSet<ArticleLike>();
            this.ArticleVideos = new HashSet<ArticleVideo>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string Tags { get; set; }
        public string Description { get; set; }
        public int AuthorId { get; set; }
        public System.DateTime dateTime { get; set; }
        public string IP { get; set; }
        public int SubscriptionTypeId { get; set; }
        public int categoryId { get; set; }
    
        public virtual UsersAuthor UsersAuthor { get; set; }
        public virtual SubscriptionType SubscriptionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleComment> ArticleComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleFile> ArticleFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleImage> ArticleImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleLink> ArticleLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleLike> ArticleLikes { get; set; }
        public virtual ArticlePublished ArticlePublished { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleVideo> ArticleVideos { get; set; }
        public virtual Category Category { get; set; }
    }
}
