//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDJArticle15.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdjArticleEntities : DbContext
    {
        public bdjArticleEntities()
            : base("name=bdjArticleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddManager> AddManagers { get; set; }
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<ArticleComment> ArticleComments { get; set; }
        public virtual DbSet<ArticleFile> ArticleFiles { get; set; }
        public virtual DbSet<ArticleImage> ArticleImages { get; set; }
        public virtual DbSet<ArticleLike> ArticleLikes { get; set; }
        public virtual DbSet<ArticleLink> ArticleLinks { get; set; }
        public virtual DbSet<ArticlePublished> ArticlePublisheds { get; set; }
        public virtual DbSet<ArticleVideo> ArticleVideos { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<LiveMessage> LiveMessages { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<SubscriptionType> SubscriptionTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersAdmin> UsersAdmins { get; set; }
        public virtual DbSet<UsersAuthor> UsersAuthors { get; set; }
        public virtual DbSet<UsersSubscription> UsersSubscriptions { get; set; }
        public virtual DbSet<UsersVerified> UsersVerifieds { get; set; }
        public virtual DbSet<vwArticlePublished> vwArticlePublisheds { get; set; }
        public virtual DbSet<vwArticleUnPublished> vwArticleUnPublisheds { get; set; }
    }
}
