//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDJArticle15.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ArticleComments = new HashSet<ArticleComment>();
            this.ArticleLikes = new HashSet<ArticleLike>();
            this.ArticlePublisheds = new HashSet<ArticlePublished>();
            this.LiveMessages = new HashSet<LiveMessage>();
            this.LiveMessages1 = new HashSet<LiveMessage>();
            this.UsersSubscriptions = new HashSet<UsersSubscription>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Contact { get; set; }
        public string Image { get; set; }
        public int GenderId { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public System.DateTime joinDate { get; set; }
        public string IP { get; set; }
        public string Address { get; set; }
        public int CityId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleComment> ArticleComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleLike> ArticleLikes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticlePublished> ArticlePublisheds { get; set; }
        public virtual City City { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiveMessage> LiveMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiveMessage> LiveMessages1 { get; set; }
        public virtual UsersAdmin UsersAdmin { get; set; }
        public virtual UsersAuthor UsersAuthor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersSubscription> UsersSubscriptions { get; set; }
        public virtual UsersVerified UsersVerified { get; set; }
    }
}
